version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: pawscross_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pawscross
      MYSQL_USER: vet_admin
      MYSQL_PASSWORD: vet_password
    ports:
      - "3310:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  api:
    build: .
    container_name: pawscross_node
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=vet_admin
      - DB_PASSWORD=vet_password
      - DB_NAME=pawscross
      - DB_PORT=3306
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    command: npm run dev

volumes:
  mariadb_data:
